# Generated by Django 3.1 on 2021-06-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rider',
            new_name='User',
        ),
    ]
