# Generated by Django 3.1 on 2021-06-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likelist',
            old_name='rider',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rider',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.FloatField(),
        ),
    ]
