# Generated by Django 3.1 on 2021-07-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210701_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='addtocart',
            new_name='add',
        ),
    ]
